# Generated by Django 2.2.1 on 2019-05-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congregacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=8)),
                ('dia_meio', models.CharField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')], max_length=1)),
                ('hora_meio', models.TimeField()),
                ('dia_fim', models.CharField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')], max_length=1)),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Publicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Limpeza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('indicador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicador1', to='mysite.Publicador')),
                ('indicador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicador2', to='mysite.Publicador')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='assistente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistente', to='mysite.Publicador'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='local',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.Local'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='publicadores',
            field=models.ManyToManyField(related_name='publicadores', to='mysite.Publicador'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='superior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superior', to='mysite.Publicador'),
        ),
        migrations.CreateModel(
            name='ConferenciaPublica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('esboco', models.CharField(max_length=3)),
                ('horario', models.TimeField()),
                ('congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Congregacao')),
                ('orador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Publicador')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenciaOutra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('titulo', models.CharField(max_length=80)),
                ('orador', models.CharField(max_length=40)),
                ('Congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Congregacao')),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')], max_length=1)),
                ('hora', models.TimeField()),
                ('dirigente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.Publicador')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.Local')),
            ],
        ),
    ]
