# Generated by Django 2.2.1 on 2019-05-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregacao',
            name='dia_fim',
            field=models.CharField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')], max_length=7),
        ),
        migrations.AlterField(
            model_name='congregacao',
            name='dia_meio',
            field=models.CharField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')], max_length=7),
        ),
    ]
